import { NextPage } from 'next';
import Head from 'next/head';

import { SocialTemplate } from '@/components/templates/SocialTemplate';

const Social: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie - Social</title>
      </Head>

      <main>
        <SocialTemplate />
      </main>
    </>
  );
};

export default Social;
