import { NextPage } from 'next';
import Head from 'next/head';

import { EnterprisesTemplate } from '@/components/templates/EnterprisesTemplate';

const Enterprises: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie - Empresas</title>
      </Head>

      <main>
        <EnterprisesTemplate />
      </main>
    </>
  );
};

export default Enterprises;
