import { NextPage } from 'next';
import Head from 'next/head';

import { Footer } from '@/components/molecules/Footer';
import { Header } from '@/components/molecules/Header';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie - Sobre a Hublie</title>
      </Head>

      <main>
        <Header />
        <h1>Sobre a Hublie</h1>
        <Footer />
      </main>
    </>
  );
};

export default About;
