import { NextPage } from 'next';
import Head from 'next/head';

import { AboutTemplate } from '@/components/templates/AboutTemplate';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie - Sobre a Hublie</title>
      </Head>

      <main>
        <AboutTemplate />
      </main>
    </>
  );
};

export default About;
