import { NextPage } from 'next';
import Head from 'next/head';

import { RecruitersTemplate } from '@/components/templates/RecruitersTemplate';

const Recruiters: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie - Recrutadores</title>
      </Head>

      <main>
        <RecruitersTemplate />
      </main>
    </>
  );
};

export default Recruiters;
