import { NextPage } from 'next';
import Head from 'next/head';

import { CandidatesTemplate } from '@/components/templates/CandidatesTemplate';

const Candidates: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie - Candidatos</title>
      </Head>

      <main>
        <CandidatesTemplate />
      </main>
    </>
  );
};

export default Candidates;
