import { NextPage } from 'next';
import Head from 'next/head';

import { HomeTemplate } from '@/components/templates/HomeTemplate';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie</title>
      </Head>

      <main>
        <HomeTemplate />
      </main>
    </>
  );
};

export default Home;
