import { NextPage } from 'next';
import Head from 'next/head';

import { DownloadAppsCard } from '@/components/molecules/DownloadAppsCard';
import { Header } from '@/components/molecules/Header';
import { Hero } from '@/components/molecules/Hero';
import { ContainerWrapper } from '@/components/quarks/ContainerWrapper';

// import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie</title>
      </Head>

      <main>
        <Header />

        <Hero />

        <div style={{ padding: '120px 148px' }}>
          <ContainerWrapper>
            <DownloadAppsCard />
          </ContainerWrapper>
        </div>
      </main>
    </>
  );
};

export default Home;
