import { NextPage } from 'next';
import Head from 'next/head';

import { Text } from '@/components/Text';

// import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />

        <title>Hublie</title>
      </Head>

      <main>
        <h1>Hublie</h1>

        <Text weight="medium">Acesse a plataforma</Text>
      </main>
    </>
  );
};

export default Home;
