import { NextPage } from 'next';
import Head from 'next/head';

import { ButtonLink } from '@/components/atoms/ButtonLink';
import { Logo } from '@/components/atoms/Logo';
import { Text } from '@/components/atoms/Text';

// import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.png" />

        <title>Hublie</title>
      </Head>

      <main>
        <h1>Hublie</h1>

        <Logo size="sm" />

        <ButtonLink href="/">
          <Text size="sm" weight="medium">
            Acesse a plataforma
          </Text>
        </ButtonLink>
      </main>
    </>
  );
};

export default Home;
